language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust:
      - nightly
      - beta
script:
  - cargo build --verbose --all
  - cargo test --verbose
  - cargo build --verbose --no-default-features
