name: Security audit
on:
  pull_request:
    paths: Cargo.lock
  schedule:
    - cron: '0 0 * * *'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:

      - name:          Cancel Previous Runs
        uses:          styfle/cancel-workflow-action@9f10b1b9fa56e99e4c5d12c2a085c8a0c37ab0ac # 0.10.0

      - name:          Checkout sources
        uses:          actions/checkout@v3.0.2
        with:
          fetch-depth: 50

      - name:          Run cargo audit
        uses:          actions-rs/audit-check@v1.2.0
        with:
          token:       ${{ secrets.GITHUB_TOKEN }}
